# Generated by Django 4.2.3 on 2023-07-07 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Toy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
            ],
            options={
                "verbose_name": "Juguete",
                "verbose_name_plural": "Juguetes",
            },
        ),
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pets.pet",
                        verbose_name="Mascota",
                    ),
                ),
                (
                    "toy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="toys.toy",
                        verbose_name="Juguete",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
