# Generated by Django 4.2.3 on 2023-07-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="pets/", verbose_name="Foto"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(max_length=50, verbose_name="Nombre corto"),
                ),
            ],
            options={
                "verbose_name": "Mascota",
                "verbose_name_plural": "Mascotas",
            },
        ),
    ]
